# Generated by Django 5.2.5 on 2025-08-20 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirdOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirdGenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.birdfamily')),
            ],
            options={
                'unique_together': {('name', 'family')},
            },
        ),
        migrations.AddField(
            model_name='birdfamily',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.birdorder'),
        ),
        migrations.CreateModel(
            name='BirdSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.birdgenus')),
                ('bird_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birds.birdtype')),
                ('habitats', models.ManyToManyField(to='birds.habitat')),
            ],
        ),
        migrations.CreateModel(
            name='BirdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='birds/photos/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.birdspecies')),
            ],
        ),
        migrations.CreateModel(
            name='BirdObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_observed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('gbif_id', models.CharField(blank=True, max_length=50, null=True)),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, to='birds.birdphoto')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.birdspecies')),
            ],
            options={
                'ordering': ['-date_observed'],
            },
        ),
        migrations.CreateModel(
            name='BirdDistributionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ImageField(upload_to='birds/maps/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birds.birdspecies')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='birdfamily',
            unique_together={('name', 'order')},
        ),
    ]
