# Generated by Django 5.2.5 on 2025-08-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='bird_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='birds.birdtype'),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='habitats',
            field=models.ManyToManyField(blank=True, null=True, to='birds.habitat'),
        ),
    ]
